### ISSUE TITLE
Breaks next.js 14

### ISSUE THREAD

**Issue by NayamAmarshe** [CristianoStav/import-formatter#1]
Hi, Next.js components require a `"use client";` at the top of the file sometimes but with this extension, it moves the `"use client";` after imports and then also puts it in `()`. This causes the server to break. Could you please add an exception?

Thank you!

**Comment by CristianoStav** [comment]
Hello @NayamAmarshe, i will add :)

**Comment by CristianoStav** [comment]
@NayamAmarshe can you test again ? I have commited a new version and in think the problem is soved.
